FROM gitlab.internal.digitex.fun:443/developers/dependency_proxy/containers/node:latest

RUN apt-get update

RUN npm install -g npm@latest
RUN node -v && npm -v

RUN npm fund

COPY . /var/project
WORKDIR /var/project

RUN npm install -g redoc-cli

CMD redoc-cli bundle ./docs/openapi.yml --output ./resources/views/docs/documents.html
CMD redoc-cli serve ./docs/openapi.yml --output ./resources/views/docs/documents.html --host 0.0.0.0 --port 8083 --watch true
