version: "3.7"
services:
  app:
    build:
      context: ./
      args:
        WORKAROUND: 'local'
      dockerfile: ./Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: rest-api
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - rest
    ports:
      - "9000:9000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    ports:
      - 8082:80
    volumes:
      - ./:/var/www/html
    networks:
      - rest
    command: [
        "/bin/sh",
        "-c",
        "sed -i 's/127.0.0.1/app/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ]

  node:
    build:
      context: ./
      dockerfile: ./Dockerfile.docs
    restart: unless-stopped
    tty: true
    ports:
    - 8083:8083
    volumes:
      - ./:/var/project
    networks:
      - rest

  consul-template:
    depends_on:
      - app
    image: rest-api
    command: [ "/bin/sh","-c", "/consul-template -consul-addr=consul-blockster:8500 -template=/app/docker/.env.ctmpl:/app/.env" ]
    restart: unless-stopped
    volumes:
      - ./:/app
    networks:
      - rest

networks:
  rest:
    external:
      name: blockster-local-network
